home/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('init_welcome', views.init_welcome, name='init_welcome'),
    # path('init_networks', views.init_networks, name='init_networks'),
    path('init_nslc', views.init_nslc, name='init_nslc'),
    path('init_source', views.init_source, name='init_source'),
    path('init_config', views.init_config, name='init_config'),
    path('init_monitoring', views.init_monitoring, name='init_monitoring'),
    path('init_qcconfig', views.init_qcconfig, name='init_qcconfig'),
    path('init_finish', views.init_finish, name='init_finish'),
    path('import_nslc',views.import_nslc, name='import_nslc'),
    path('about', views.about, name='about'),
    # path('old', views.index_old, name='index.old')
]

morumotto/urls.py
# -*- coding: utf-8 -*-
"""morumotto URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf import settings
from django.conf.urls import url
from home import views as home_views
from . import celery
import object_tools

urlpatterns = [
    path('admin/', admin.site.urls), # URL FOR ADMIN PAGE
    path('home/', include('django.contrib.auth.urls')), #URL FOR AUTHENTICATION PAGE
    # path('accounts/login/', admin.site.urls),
    path('', home_views.go_to_home, name='home'),
    path('home/', include('home.urls')),
    # path('login/', home_views.login, name="login"),
    # path('logout/', home_views.logout, name="logout"),
    path('archive/',include('archive.urls')),
    path('monitoring/',include('monitoring.urls')),
    path('qualitycontrol/',include('qualitycontrol.urls')),
    path('celery_progress/', include('celery_progress.urls')),  # the endpoint is configurable
    # url(r'^celery-progress/', include('celery_progress.urls')),
    path('flower', home_views.flower_redirect, name='flower_redirect'),
    path('rtfm', home_views.documentation_redirect, name='documentation_redirect'),
    path('object-tools/', object_tools.tools.urls),
]

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.index_title = settings.ADMIN_INDEX_TITLE
admin.site.site_title = settings.ADMIN_SITE_TITLE

archive/models.py
# -*- coding: utf-8 -*-
import os
import importlib
import logging
import tempfile
from datetime import datetime
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError
from django.utils.timezone import now
from plugins.choices import get_plugin_choices

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORKING_DIR =  os.path.join(BASE_DIR, "WORKING_DIR/")
logger = logging.getLogger('Status')

class Network(models.Model):
    name = models.CharField(max_length=10, unique=True)
    def __str__(self):
        return self.name


class Station(models.Model):
    network = models.ForeignKey(Network,on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    multiplexing = models.BooleanField(default="False",
                                       verbose_name="Multiplexed Channels")

    def __str__(self):
        name_to_display = "[%s] %s" %(self.network.name, self.name)
        return name_to_display

    class Meta:
        ordering = ('network','name',)


class Location(models.Model):
    name = models.CharField(max_length=10, unique=True)
    def __str__(self):
        return self.name


class Channel(models.Model):
    name = models.CharField(max_length=10, unique=True)
    def __str__(self):
        return self.name


class NSLC(models.Model):
    net = models.ForeignKey(Network,on_delete=models.CASCADE,
                            verbose_name="network")
    sta = models.ForeignKey(Station,on_delete=models.CASCADE,
                            verbose_name="station")
    loc = models.ForeignKey(Location,on_delete=models.CASCADE,
                            verbose_name="location")
    chan = models.ForeignKey(Channel,on_delete=models.CASCADE,
                            verbose_name="channel")
    code = models.CharField(max_length=50,default=None)

    def save(self, *args, **kwargs):
        self.code = '{0}.{1}.{2}.{3}'.format(self.net.name, self.sta.name,
                                             self.loc, self.chan)
        super(NSLC, self).save(*args, **kwargs)

    def __str__(self):
        return self.code

    class Meta:
        ordering = ('net','sta','chan')
        verbose_name = 'N.S.L.C.'
        verbose_name_plural = 'N.S.L.C'

class PluginField(models.Field):
    def __init__(self, type, *args, **kwargs):
        self.max_length = max_length
        super().__init__(*args, **kwargs)

    def db_type(self, connection):
        return 'char(%s)' % self.max_length


class Source(models.Model):
    SOURCE_LOG_CHOICES =(
        (1, '1 : Error'),
        (2, '2 : Warning'),
        (3, '3 : Debug'),
    )
    SOURCE_CHOICES = get_plugin_choices("source")
    name = models.CharField(
         max_length=50,
         help_text='Please avoid spaces (they will automaticaly '
                   'be replaced with underscores)')
    priority = models.PositiveIntegerField(
             default=1,
             help_text='1 is the highest priority',
             validators=[MinValueValidator(1)],
             )
    log_level = models.IntegerField(
              choices=SOURCE_LOG_CHOICES,
              default=3)
    type = models.CharField(
         max_length=50,
         choices=SOURCE_CHOICES,
         verbose_name="Plugin",
         )
    parameters = models.CharField(max_length=50,blank=True)
    limit_rate = models.IntegerField(
               default=0,
               verbose_name="Downloading limit rate",
               help_text='Limit for downloading rate, '
                         'in Kb/s. 0 is for unlimited')
    cpu_limit = models.IntegerField(
              default=100,
              verbose_name="CPU limit",
              help_text='Percentage  of  CPU allowed. Defaults to 100%')

    is_online = models.BooleanField(default=True)
    availability = models.BooleanField(
                 default=True,
                 help_text='If False (unselected), '
                           'the software will assume that data is '
                           'always available for all time')
    nslc = models.ManyToManyField(NSLC,verbose_name='N.S.L.C',
                                  help_text=('Select all NSLC that this source'
                                             ' will query, unselected will be'
                                             ' ignored.')
                                 )

    def __str__(self):
        return self.name

    def get_plugin(self):
        # We will instanciate the correct class according to the source type.
        # See plugins/source.py
        try:
            module = importlib.import_module("plugins.source")
            class_ = getattr(module, self.type)
            return class_()
        except:
            logger.error("ERROR: %s has not yet been correctly implemented."
                  " See plugins/source.py" % self.type)
            return 1

    # def get_parameters_template(self):
    #     # Returns template for parameters.
    #     # See plugins/source.py
    #     try:
    #         module = importlib.import_module("plugins.source")
    #         class_ = getattr(module, self.type)
    #         return class_().template
    #     except:
    #         logger.error("ERROR: %s has not yet been correctly implemented."
    #               " See plugins/source.py" % self.type)
    #         return 1

    def save(self, *args, **kwargs):
        self.name = self.name.replace(" ", "_")
        super(Source, self).save(*args, **kwargs)

    class Meta:
        ordering = ('priority',)


class Configuration(models.Model):
    FREQ_CHOICES =(
        ('hourly', 'Hours'),
        ('daily', 'Days'),
    )
    LIFESPAN_CHOICES = (
        ('n', 'Number of retry'),
        ('p', 'Period (in hours)'),
    )
    BLOCKSIZE_CHOICES = (
        (512,512),
        (4096,4096),
    )

    COMPRESS_CHOICES =(
        ('STEIM1', 'STEIM1'),
        ('STEIM2', 'STEIM2'),
        ('INT_16', 'INT_16'),
        ('INT_32','INT_32'),
        ('INT_24','INT_24'),
		('IEEE_FP_SP', 'IEEE_FP_SP'),
        ('IEEE_FP_DP','IEEE_FP_DP'),
    )

    QC_CHOICES =(
        ('D', 'D (indeterminate)'),
        ('R', 'R (raw waveform)'),
        ('Q', 'Q (quality controlled data)'),
        ('M', 'M (data center modified)'),
    )

    DATAFORMAT_CHOICES = get_plugin_choices("format")
    # METADATAFORMAT_CHOICES = get_plugin_choices("metadata_format")
    STRUCT_CHOICES = get_plugin_choices("structure")

    name = models.CharField(
                max_length=50,
                default="MORUMOTTO_CONFIG")
    archive = models.CharField(
            max_length=50,
            help_text='Absolute path to your final archive',
            default=os.path.join(BASE_DIR,"final_archive"))

    networks = models.ManyToManyField(Network)
    stations = models.ManyToManyField(Station)
    nslc = models.ManyToManyField(NSLC,verbose_name='N.S.L.C')
    sources = models.ManyToManyField(Source, blank=True)
    data_format = models.CharField(
                max_length=50,
                choices=DATAFORMAT_CHOICES,
                default='miniSEED')
    # metadata_format = models.CharField(
    #                 max_length=50,
    #                 choices=METADATAFORMAT_CHOICES,
    #                 default='DatalessSEED')
    struct_type = models.CharField(
                max_length=50,
                choices=STRUCT_CHOICES,
                default='SDS',
                verbose_name='Structure type')
    blocksize = models.PositiveSmallIntegerField(
              choices=BLOCKSIZE_CHOICES,
              default=4096,
              verbose_name='Blocksize, in bytes')
    compression_format = models.CharField(
                       max_length=50,
                       choices=COMPRESS_CHOICES,
                       default='STEIM2')
    quality_label = models.CharField(
                  max_length=5,
                  choices=QC_CHOICES,
                  default='M')
    request_lifespan_type = models.CharField(
                          max_length=50,
                          choices=LIFESPAN_CHOICES,
                          default='n')
    request_lifespan = models.PositiveSmallIntegerField(
                     default=5,
                     validators=[MinValueValidator(1)],
                     help_text='Either a number of retry OR '
                               'a lifespan in hours '
                               '(depending on the previous field)')
    n_request = models.PositiveSmallIntegerField(
              default=10,
              validators=[MinValueValidator(1), MaxValueValidator(100)],
              help_text='Number of request parallel threads')
    max_gaps_by_analysis = models.PositiveSmallIntegerField(
                         default=10,
                         validators=[MinValueValidator(1)],
                         help_text='If the number of gaps inside the window of '
                                   'analysis is over this threshold, they will '
                                   'be merged into 1 gap starting with the '
                                   'first gap starttime and ending with the '
                                   'last gap endtime')
    initialisation = models.BooleanField(
                   default=True,
                   help_text='Check if you want to initialise '
                             'the software again (not recommanded)')
    debug_mode = models.BooleanField(
               default=True,
               help_text='Check if you want to keep all data downloaded '
                         'for patching')
    crontab_status = models.BooleanField(
                   default=False,
                   help_text='True if a crontab is running, else False')
    granularity_type = models.CharField(
                     max_length=6,
                     choices=FREQ_CHOICES,
                     default='hourly')
    f_analysis = models.PositiveSmallIntegerField(
               default=1,

logdb/models.py
# -*- coding: utf-8 -*-
import logging
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

LOG_LEVELS = (
    (logging.NOTSET, _('NotSet')),
    (logging.INFO, _('Info')),
    (logging.WARNING, _('Warning')),
    (logging.DEBUG, _('Debug')),
    (logging.ERROR, _('Error')),
    (logging.FATAL, _('Fatal')),
)


@python_2_unicode_compatible
class StatusLog(models.Model):
    logger_name = models.CharField(max_length=100)
    level = models.PositiveSmallIntegerField(choices=LOG_LEVELS, default=logging.ERROR, db_index=True)
    msg = models.TextField()
    trace = models.TextField(blank=True, null=True)
    create_datetime = models.DateTimeField(auto_now_add=True, verbose_name='Created at')

    def __str__(self):
        return self.msg

    class Meta:
        ordering = ('-create_datetime',)
        verbose_name_plural = verbose_name = 'Software Log'

@python_2_unicode_compatible
class MonitoringLog(models.Model):
    logger_name = models.CharField(max_length=100)
    level = models.PositiveSmallIntegerField(choices=LOG_LEVELS, default=logging.ERROR, db_index=True)
    msg = models.TextField()
    trace = models.TextField(blank=True, null=True)
    create_datetime = models.DateTimeField(auto_now_add=True, verbose_name='Created at')

    def __str__(self):
        return self.msg

    class Meta:
        ordering = ('-create_datetime',)
        verbose_name_plural = verbose_name = 'Monitoring Log'

@python_2_unicode_compatible
class UpdateLog(models.Model):
    logger_name = models.CharField(max_length=100)
    level = models.PositiveSmallIntegerField(choices=LOG_LEVELS, default=logging.ERROR, db_index=True)
    msg = models.TextField()
    trace = models.TextField(blank=True, null=True)
    create_datetime = models.DateTimeField(auto_now_add=True, verbose_name='Created at')

    def __str__(self):
        return self.msg

    class Meta:
        ordering = ('-create_datetime',)

@python_2_unicode_compatible
class QCLog(models.Model):
    logger_name = models.CharField(max_length=100)
    level = models.PositiveSmallIntegerField(choices=LOG_LEVELS, default=logging.ERROR, db_index=True)
    msg = models.TextField()
    trace = models.TextField(blank=True, null=True)
    create_datetime = models.DateTimeField(auto_now_add=True, verbose_name='Created at')

    def __str__(self):
        return self.msg

    class Meta:
        ordering = ('-create_datetime',)

@python_2_unicode_compatible
class StatsLog(models.Model):
    logger_name = models.CharField(max_length=100)
    level = models.PositiveSmallIntegerField(choices=LOG_LEVELS, default=logging.ERROR, db_index=True)
    msg = models.TextField()
    trace = models.TextField(blank=True, null=True)
    create_datetime = models.DateTimeField(auto_now_add=True, verbose_name='Created at')

    def __str__(self):
        return self.msg

    class Meta:
        ordering = ('-create_datetime',)

@python_2_unicode_compatible
class StackLog(models.Model):
    logger_name = models.CharField(max_length=100)
    level = models.PositiveSmallIntegerField(choices=LOG_LEVELS, default=logging.ERROR, db_index=True)
    msg = models.TextField()
    trace = models.TextField(blank=True, null=True)
    create_datetime = models.DateTimeField(auto_now_add=True, verbose_name='Created at')

    def __str__(self):
        return self.msg

    class Meta:
        ordering = ('-create_datetime',)

@python_2_unicode_compatible
class PluginsLog(models.Model):
    logger_name = models.CharField(max_length=100)
    level = models.PositiveSmallIntegerField(choices=LOG_LEVELS, default=logging.ERROR, db_index=True)
    msg = models.TextField()
    trace = models.TextField(blank=True, null=True)
    create_datetime = models.DateTimeField(auto_now_add=True, verbose_name='Created at')

    def __str__(self):
        return self.msg

    class Meta:
        ordering = ('-create_datetime',)

home/templates/home/footer.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'home/css/home.css' %}">

<footer class="footer">

  <!-- <p>
    <a href="https://www.resif.fr/">
      <img src="{% static 'home/images/logo_resif.png' %}"  alt="Logo resif" width="25" height="25">
    </a>
  </p> -->
  <nav class="navbar navbar-expand-sm navbar-light bg-light">

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link py-0" href='{% static "/docs/user_guide.html" %}'>Docs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link py-0" href="{% url 'about' %}" id="aboutBtn">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link py-0" href="mailto:geber@ipgp.fr">Contact</a>
        </li>

        <!-- <li class="nav-item">
          <a class="nav-link py-0" href="#">License</a>
        </li> -->

        <li class="nav-item">
          <a class="nav-link py-0" href="https://www.resif.fr/">
            <img src="{% static 'home/images/logo_resif.png' %}"  alt="Logo resif" height="25" width="110">
          </a>
        </li>

      </ul>
    </div>
  </nav>


</footer>

home/templates/home/index.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Morumotto</title>
    {% include "home/headers/datatable.html" %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/home.css' %}">
  </head>
  <body>
    {% include "home/header.html" %}
    {% if initialise %}
    {% include "home/initialisation.html" %}
    {% endif %}
    <div class="container">
      <br>
      <div>
        <center>
          {% if user.is_authenticated %}
          <form method="post">
            {% csrf_token %}
            {% if not running %}
              <span class="icon-input-btn"><span class="far fa-play-circle"></span>
                <input type="submit" class="btn btn-success" name="start_update"
                id="startCron" value="Start automatic data update">
              </span>
            {% else %}
              <span class="icon-input-btn"><span class="far fa-stop-circle"></span>
                <input type="submit" class="btn btn-danger" name="stop_update"
                id="stopCron" value="Stop automatic data update">
              </span>
            {% endif %}
          </form>
          {% else %}
            {% if not running %}
              <button type="button" class="btn btn-success" title="Sign in to use" disabled><i class="far fa-play-circle" ></i>&nbsp; Start automatic data update</button>
            {% else %}
              <button type="button" class="btn btn-danger" title="Sign in to use" disabled><i class="far fa-stop-circle"></i>&nbsp; Stop automatic data update</button>
            {% endif %}
          {% endif %}
        </center>
      </div>
      <br><hr><br>
      {% include "home/log_table.html" %}
    </div>

    {% include "home/footer.html" %}

    <script type="text/javascript">

        function get_template() {
          var pluginField = document.getElementById("id_type").value;
          {% for key, val in parameters.items %}
            if (pluginField == "{{ key }}") {
              {% autoescape on %}
                $('#id_parameters').attr('placeholder', "{{ val|safe }}")
              {% endautoescape %}
            }
          {% endfor %}
        }


       function update_value(){
         drawTimeline()
       }

       function drawTimeline() {
         $('#hoverRes').find('.coloredDiv').css('background-color',"white");
         $('#hoverRes').find('#timelineLegend').text("");
         var width = 400;
         var f_analysis=parseInt(document.getElementById("id_f_analysis").value);
         var w_analysis=parseInt(document.getElementById("id_w_analysis").value);
         var l_analysis=parseInt(document.getElementById("id_l_analysis").value);
         var granularity=document.getElementById("id_granularity_type").value;
         if (granularity === "daily") {
             var gran = 3600*24;
             var unit = "day(s)"
         } else {
             var gran = 3600;
             var unit = "hour(s)"
         };

         var utcTimestamp = moment.utc().startOf('hour').valueOf()
         var now = parseInt(utcTimestamp)
         var windowStart = now-(l_analysis+w_analysis)*gran*1000
         var newDataStart = now-(l_analysis+f_analysis)*gran*1000
         var windowEnd = now-l_analysis*gran*1000
         var windowSize = (l_analysis+w_analysis)
         var oldData = windowStart - 5*gran*1000
         // alert(moment.utc(windowStart).format() + ", " + moment.utc(newDataStart).format() + ", " + moment.utc(windowEnd).format() + ", " + moment.utc(now).format())
         var windowTimes = [
         //  {class: "Start", times: [{"color":"#007bff", "label":"Analysis", "starting_time": windowStart, "ending_time": newDataStart}]},
         //  {class: "New data to be analyzed", times: [{"color":"#84e19a", "label":"New", "starting_time": newDataStart, "ending_time": windowEnd}, ]},
         //  {class: "Latency of analysis", times: [{"color":"#e9ecef", "label":"Latency", "starting_time": windowEnd, "ending_time": now}]}
         // ];
             {label: "Window",
               total_time: "Window length is ".concat(' ',w_analysis,unit),
               times: [{"color":"#ffc107",
                        "legend": "Old data. Not updated anymore",
                        "starting_time": oldData,
                        "ending_time": windowStart,
                        "total_time": ""},
                        {"color":"#28a745",
                        "legend": " Data to be updated",
                        "starting_time": windowStart,
                        "ending_time": newDataStart,
                        "total_time":
                          "Length: ".concat(' ', w_analysis-f_analysis,' ', unit), },
                        {"color":"#84e19a",
                         "legend": " New data",
                         "starting_time": newDataStart,
                         "ending_time": windowEnd,
                         "total_time":
                          "Length: ".concat(' ', f_analysis, ' ', unit), },
                      ]},
             {label: "Latency",
               times: [{"color":"#e9ecef",
                        "legend": "Latency of analysis",
                        "starting_time": windowEnd,
                        "ending_time": now,
                        "total_time": "Length: ".concat(' ',l_analysis,' ', unit)},
                      ]}
        ];

         var chart = d3.timeline()
           // .relativeTime()
           // .beginning(windowStart)
           // .ending(now)
           // .rotateTicks(45)
           .tickFormat({
             format: function(d) { return d3.time.format("%m/%d %H:%M")(d) },
             tickTime: d3.time.hours,
              // tickInterval: 4*windowSize,
              numTicks: 3,
              tickSize: 12,
           })
           .stack()
           .margin({left:80, right:40, top:0, bottom:0})
           .hover(function (d, i, datum) {
           // d is the current rendering object
           // i is the index during d3 rendering
           // datum is the id object
             var div = $('#hoverRes');
             div.find('.coloredDiv').css('background-color',d.color)
             if (d.starting_time != oldData){
               div.find('#timelineLegend').text(d.legend + ". From: " +
               moment.utc(d.starting_time).format("YYYY/MM/DD HH:mm") +
               " to: " + moment.utc(d.ending_time).format("YYYY/MM/DD HH:mm")
                + ". " + d.total_time );
                document.getElementById("timelineLegend").style.marginBottom = "0px";
              }
             else {
               div.find('#timelineLegend').text(d.legend)
               document.getElementById("timelineLegend").style.marginBottom = "24px";

             }
           })
           // .hover(function (d, i, datum) {
           // // d is the current rendering object
           // // i is the index during d3 rendering
           // // datum is the id object
           //   var div = $('#hoverRes');
           //   div.find('#name').text(datum.class);
           // })
         d3.select('#timeline3').selectAll('svg').remove()
         var svg = d3.select("#timeline3").append("svg").attr("width", width)
           .datum(windowTimes).call(chart);


       }


      $(document).ready(function() {
        $("#homeBtn").addClass("active");
        $("#initModal").modal('show');
        $('#initModal').on('shown.bs.modal', function (e) {
          {% if modal == "config" %}
            drawTimeline();
          {% endif %}
        })
        $('#initModal').on('hidden.bs.modal', function (e) {
          var pageURL = window.location.href.split("/home")[0];
          newPageURL = pageURL + "/home";
          window.location.replace(newPageURL)
        })

        $('#add_more').click(function() {
             var form_idx = $('#id_form-TOTAL_FORMS').val();
             $('#form_set').append($('#empty_form').html().replace(/__prefix__/g, form_idx));
             $('#id_form-TOTAL_FORMS').val(parseInt(form_idx) + 1);
         });

         $('.has-popover').tooltip({'trigger':'hover'});

         $("#closeModal").click(function(){
           var ajaxReq = $.ajax({
             method: "POST",
             data: $('#closeModal').serialize()
           })
         });

         {% if import %}
            $("#importNSLC").modal('show');
         {% endif %}
         $('#importNSLC').on('hidden.bs.modal', function (e) {
           var pageURL = window.location.href.split("/home")[0];
           newPageURL = pageURL + "/home";
           window.location.replace(newPageURL)
         })
         // {% if messages %}
         //   {% for message in messages %}
         //     alert('{{ message }}');
         //   {% endfor %}
         // {% endif %}


         // $("#id_crontime").data("DateTimePicker").minDate(new Date());


       });
    </script>
  </body>
</html>

home/templates/home/init_finish.html
<form method="post">
  {% csrf_token %}
  <div class="modal-body ">
    <div class="alert alert-success" role="alert">
       <h4 class="alert-heading"><i class="fas fa-check text-success"></i> All Done, you can use Morumotto now !</h4>
    </div>
  </div>
  <div class="modal-footer">
    <input type="submit" class="btn btn-primary" name="finish_prev" value="&#8592 Prev">
    <input type="submit" class="btn btn-success" name="finished" value="Close">
  </div>
</form>

home/templates/home/init_monitoring.html
<form method="post">
  {% csrf_token %}
  <div class="modal-body ">
    <div class="alert alert-success" role="alert">
       <h4 class="alert-heading">Configure Monitoring</h4>
    </div>
    <hr>
    <span style="font-size: 1em" class="text-secondary">
        {% for field in monitoring_form %}
          <div class="submit-link-row">{{ field.label_tag }} {{ field }}</div>
          {% if monitoring_form.errors %}
            {% for error in field.errors %}
              <p class="error-message" style="color:red">
                <strong>{{ error|escape }}</strong>
              </p>
            {% endfor %}
          {% endif %}
        {% endfor %}
    </div>
    <div class="modal-footer">
      <input type="submit" class="btn btn-primary" name="monitoring_prev" value="&#8592 Prev">
      <input type="submit" class="btn btn-primary" name="monitoring_next" value="Next &#8594">
    </div>
  </form>

home/templates/home/log_table.html
{% load datetime_to_str %}
<div class="row">
  <div class="col-11">
    <h6><b> Last actions : </b></h6>
  </div>
  <div class="col-1">
    <a class="btn btn-primary fas fa-sync-alt" title="Refresh" href="/home"></a>
    <!-- <button class="btn btn-primary" value="Refresh Page" onClick="window.location.reload();">Refresh</button> -->
  </div>
</div>
<table id='table_id' class="display" style="width:100%">
  <thead>
    <tr>
      <th align="center">Date (UTC)</th>
      <th align="center">Log type</th>
      <th align="center">Level</th>
      <th align="center">Last Message</th>
    </tr>
  </thead>
  <tbody>
    {% for log in log_messages %}
      <tr>
        <td style="width: 80px">{{ log.create_datetime|datetime_to_str }}</td>
        <td style="width: 100px">{{ log.logger_name }}</td>
        <td style="width: 100px">{{ log.get_level_display }}</td>
        <td>{{ log.msg }}</td>
      </tr>
    {% endfor %}
    {% if last_cron %}
      <tr>
        <td style="width: 80px">{{ last_cron_date|datetime_to_str  }}</td>
        <td style="width: 120px">Crontab</td>
        <td style="width: 100px">Info</td>
        <td>{{ last_cron }}</td>
      </tr>
    {% endif %}

  </tbody>
  <tfoot>
    <tr>
      <th>
        <button type="button" class="btn btn-sm btn-primary" disabled>
          Filtering:
        </button>
      </th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </tfoot>
</table>

<script>
  $(document).ready( function () {

  var table = $('#table_id').DataTable( {
    initComplete: function () {
      this.api().columns([1,2]).every( function () {
          var column = this;
          var select = $('<select><option value="">Show all</option></select>')
              .appendTo( $(column.footer()).empty() )
              .on( 'change', function () {
                  var val = $.fn.dataTable.util.escapeRegex(
                      $(this).val()
                  );
                  myMule = val;
                  column
                      .search( val ? '^'+val+'$' : '', true, false )
                      .draw();
              });
          column.data().unique().sort().each( function ( d, j ) {
              select.append( '<option value="' + d + '">' + d.substr(0,30) + '</option>' )
          } );
          $( select ).click( function(e) {
               e.stopPropagation();
         });
      } );
    },
    scrollX: true,
    scrollY: 450,
    scrollCollapse: true,
    paging: true,
    orderCellsTop: true,
    fixedHeader: true,
    "order": [[0,'desc']],
    "deferRender": true,
    "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],

    dom: 't',
    });

  });

</script>