home/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('init_welcome', views.init_welcome, name='init_welcome'),
    # path('init_networks', views.init_networks, name='init_networks'),
    path('init_nslc', views.init_nslc, name='init_nslc'),
    path('init_source', views.init_source, name='init_source'),
    path('init_config', views.init_config, name='init_config'),
    path('init_monitoring', views.init_monitoring, name='init_monitoring'),
    path('init_qcconfig', views.init_qcconfig, name='init_qcconfig'),
    path('init_finish', views.init_finish, name='init_finish'),
    path('import_nslc',views.import_nslc, name='import_nslc'),
    path('about', views.about, name='about'),
    # path('old', views.index_old, name='index.old')
]

morumotto/urls.py
# -*- coding: utf-8 -*-
"""morumotto URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf import settings
from django.conf.urls import url
from home import views as home_views
from . import celery
import object_tools

urlpatterns = [
    path('admin/', admin.site.urls), # URL FOR ADMIN PAGE
    path('home/', include('django.contrib.auth.urls')), #URL FOR AUTHENTICATION PAGE
    # path('accounts/login/', admin.site.urls),
    path('', home_views.go_to_home, name='home'),
    path('home/', include('home.urls')),
    # path('login/', home_views.login, name="login"),
    # path('logout/', home_views.logout, name="logout"),
    path('archive/',include('archive.urls')),
    path('monitoring/',include('monitoring.urls')),
    path('qualitycontrol/',include('qualitycontrol.urls')),
    path('celery_progress/', include('celery_progress.urls')),  # the endpoint is configurable
    # url(r'^celery-progress/', include('celery_progress.urls')),
    path('flower', home_views.flower_redirect, name='flower_redirect'),
    path('rtfm', home_views.documentation_redirect, name='documentation_redirect'),
    path('object-tools/', object_tools.tools.urls),
]

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.index_title = settings.ADMIN_INDEX_TITLE
admin.site.site_title = settings.ADMIN_SITE_TITLE

qualitycontrol/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views

urlpatterns = [
    path('', views.qc_menu, name='qc_menu'),
    path('status', views.status, name='status'),
    path('update_metadata', views.update_metadata, name='update_metadata'),
    path('check_data', views.check_data, name='check_data'),
    path('map_stations', views.map_stations, name='map_stations'),
    path('check_metadata', views.check_metadata, name='check_metadata'),
    path('metadata_vs_data', views.metadata_vs_data, name='metadata_vs_data'),
    path('plot_completion', views.plot_completion, name='plot_completion'),
    path('plot_response', views.plot_response, name='plot_response'),
]

qualitycontrol/models.py
# -*- coding: utf-8 -*-
import os
import re
import obspy
import logging
import importlib
from fnmatch import fnmatch
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError
from django.utils.timezone import now
from archive.models import NSLC
from plugins.choices import get_plugin_choices

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BIN =  os.path.join(BASE_DIR, "bin")
VALIDATOR_LINK = os.path.join(BASE_DIR, "bin","stationxml-validator.jar")

LOG_LEVELS = (
    (logging.NOTSET, _('NotSet')),
    (logging.INFO, _('Info')),
    (logging.WARNING, _('Warning')),
    (logging.DEBUG, _('Debug')),
    (logging.ERROR, _('Error')),
    (logging.FATAL, _('Fatal')),
)


def get_validator_choices():
    VALIDATOR_CHOICES = ()
    validator_list = [f for f in os.listdir(BIN) if
                      ( os.path.isfile(os.path.join(BIN, f))
                      and not os.path.islink(os.path.join(BIN, f))
                      and fnmatch(f, '*.jar') ) ]
    for validator in validator_list:
        ver = '.'.join(re.findall(r"[\d']+", validator))
        VALIDATOR_CHOICES += ((validator,ver),)

    return VALIDATOR_CHOICES


class QCConfig(models.Model):
    METADATAFORMAT_CHOICES = get_plugin_choices("metadata_format")
    archive = models.CharField(max_length=200)
    metadata_format = models.CharField(
                    max_length=50,
                    choices=METADATAFORMAT_CHOICES,
                    default='stationXML')
    metadata_validator = models.CharField(
                       max_length=50,
                       choices=get_validator_choices(),
                       default='1.5.9.5',
                       verbose_name="Metadata Validator Version",)

    def get_metadata_format(self):
        # We will instanciate the correct class according to the metadata format
        # See plugins/metadata_format.py
        try:
            module = importlib.import_module("plugins.metadata_format")
            class_ = getattr(module, self.metadata_format)
            return class_()
        except:
            logger.error("ERROR: %s has not yet been implemented."
                  " See plugins/metadata_format.py" % self.metadata_format)
            return 1
    #
    def save(self, *args, **kwargs):
        print("valid:",self.metadata_validator )
        validator_file = os.path.join(BASE_DIR, "bin",self.metadata_validator)
        if os.path.exists(VALIDATOR_LINK):
            os.remove(VALIDATOR_LINK)
        os.symlink(validator_file, VALIDATOR_LINK)
        return super(QCConfig, self).save(*args, **kwargs)

    def __str__(self):
        return self.archive

    class Meta:
        verbose_name_plural = verbose_name = 'Quality Control Configuration'


class Message(models.Model):
    TYPE_CHOICES = (
        (('info'), ('Info')),
        (('warning'), ('Warning')),
        (('debug'), ('Debug')),
        (('error'), ('Error')),
    )

    msg = models.CharField(max_length=300)
    type = models.CharField(max_length=25,
                            choices=TYPE_CHOICES,
                            default="info")
    def __str__(self):
        return self.msg


class Metadata(models.Model):

    nslc = models.ForeignKey(NSLC, on_delete=models.CASCADE,
                             verbose_name="N.S.L.C.")
    file = models.CharField(max_length=200)
    lon = models.FloatField(validators=[MinValueValidator(-180.0),
                                        MaxValueValidator(180.0)],
                            help_text="Must be a decimal value")
    lat = models.FloatField(validators=[MinValueValidator(0.0),
                                        MaxValueValidator(90.0)],
                            help_text="Must be a decimal value")
    messages = models.ManyToManyField(Message)


    def __str__(self):
        return self.nslc.code

    class Meta:
        ordering = ('nslc',)
        verbose_name_plural = verbose_name = 'Metadata'


class LastUpdate(models.Model):
    UPDATE_CHOICES=(
        ("local_dir", 'Select local dir/'),
        ("web_service", 'Use a webservice'),
        ("svn", 'Use SVN'),
    )
    time = models.DateTimeField(default=now)
    update_method = models.CharField(max_length=25,
                                     choices=UPDATE_CHOICES,
                                     default="local_dir")
    options = models.CharField(max_length=200,default="")
    class Meta:
         verbose_name = "Last Update of Metadata"
         verbose_name_plural = "Last Update of Metadata"

    def __str__(self):
        return "Last Update on %s with data from %s" %(self.time,
                                                       self.update_method)

qualitycontrol/forms.py
# -*- coding: utf-8 -*-
from django import forms
from bootstrap_datepicker_plus import DateTimePickerInput
from .models import Metadata
from archive.models import NSLC


class GetMetadataForm(forms.Form):
    METHOD_CHOICES = (
        ("local_dir", 'Select local dir/'),
        ("web_service", 'Use a webservice'),
        ("svn", 'Use SVN'),
    )
    method = forms.MultipleChoiceField(widget=forms.Select,
                                       choices=METHOD_CHOICES)

class MetadataFolderForm(forms.Form):
    dir = forms.CharField(
        label='Select Directory',
        widget=forms.TextInput(attrs={'placeholder': '/path/to/metadata',
                                      'size': '30px',
                                      'title':'Will scan all directories '
                                      'and subdirectories to find metadata'})
        )


class MetadataWSForm(forms.Form):
    client = forms.CharField(
           label='Client address :',
           widget=forms.TextInput(
                 attrs={'placeholder':
                        'http://ws.ipgp.fr',
                        'size': '30',
                        }))

class MetadataSVNForm(forms.Form):
    svn_address = forms.CharField(
                label='SVN address :',
                widget=forms.TextInput(
                      attrs={'placeholder':
                             'https://svn.ipgp.fr/ovsm/trunk/dataless/stations/',
                             'size':'40',
                             'title':'Will scan all directories '
                             'and subdirectories to find metadatas'
                             }))
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())


class MetadataForm(forms.Form):
    nslc_list = forms.ModelMultipleChoiceField(queryset=Metadata.objects.all(),
                                               widget=forms.SelectMultiple(
                                                     attrs={'size': 20}),
                                               label="Select channel(s)",
                                               )

class MetadataUniqueForm(forms.Form):
    nslc = forms.ModelChoiceField(queryset=Metadata.objects.all(),
                                  widget=forms.Select(
                                        attrs={'size': 16}),
                                  label="Select channel",
                                  )
    starttime = forms.DateTimeField(widget=DateTimePickerInput(
                                      attrs={'class': 'datetimepicker-input',
                                      'placeholder':'Not required'},
                                      format='YYYY-MM-DD HH:mm:ss'),
                                  label="Metadata Starttime",
                                  required = False)
    endtime = forms.DateTimeField(widget=DateTimePickerInput(
                                      attrs={'class': 'datetimepicker-input',
                                      'placeholder':'Not required'},
                                      format='YYYY-MM-DD HH:mm:ss'),
                                  label="Metadata Endtime",
                                  required = False)

class NSLCYearForm(forms.Form):
    nslc = forms.ModelChoiceField(queryset=NSLC.objects.all(),
                                  widget=forms.Select(
                                        attrs={'size': 20}),
                                  label="Select channel",
                                  )
    year = forms.DateField(input_formats=['%Y'],
                           widget = DateTimePickerInput(
                                  format='%Y',attrs={'size': 3}),
                           label="Select a year",)


class MetadataYearForm(forms.Form):
    nslc = forms.ModelChoiceField(queryset=Metadata.objects.all(),
                                  widget=forms.Select(
                                        attrs={'size': 17}),
                                  label="Select channel",
                                  )
    year = forms.DateField(input_formats=['%Y'],
                           widget=DateTimePickerInput(format='%Y'),
                           label="Select a year",)



class MetadataDatesForm(forms.Form):
    metadata_list = forms.ModelMultipleChoiceField(queryset=Metadata.objects.all(),
                                          widget=forms.SelectMultiple(
                                                attrs={'size': 16}),
                                          label="Select channel(s)",
                                          )
    starttime = forms.DateTimeField(widget=DateTimePickerInput(
                                      attrs={'class': 'datetimepicker-input',
                                      'placeholder':'Not required'},
                                      format='YYYY-MM-DD HH:mm:ss'),
                                    label="Metadata Starttime",
                                    required = False)
    endtime = forms.DateTimeField(widget=DateTimePickerInput(
                                      attrs={'class': 'datetimepicker-input',
                                      'placeholder':'Not required'},
                                      format='YYYY-MM-DD HH:mm:ss'),
                                  label="Metadata Endtime",
                                  required = False)


# class NewRequestForm(forms.ModelForm):
#     class Meta:
#         model = GapList
#         fields = ['nslc_list', 'starttime', 'endtime']
#         widgets = {'starttime': DateTimePickerInput(attrs={'class': 'datetimepicker-input',
#                                                             'placeholder':'Select a date',},
#                                                     format='YYYY-MM-DD HH:mm:ss'),
#                     'endtime': DateTimePickerInput(attrs={'class': 'datetimepicker-input',
#                                                           'placeholder':'Select a date'},
#                                                   format='YYYY-MM-DD HH:mm:ss'),
#                     }
#     def clean(self):
#         cleaned_data = super().clean()
#         start_date = cleaned_data.get("starttime")
#         end_date = cleaned_data.get("endtime")
#
#         if end_date and start_date:
#             if end_date < start_date:
#                 msg = "Endtime should be greater than starttime."
#                 self.add_error("endtime", msg)

qualitycontrol/templates/qualitycontrol/check_data.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Morumotto</title>
    {% include "home/headers/datepicker_datatable.html" %}
  </head>

  <body>
    {% include "home/header.html" %}
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb ">
        <li class="breadcrumb-item"><a href="/qualitycontrol">Quality Control</a></li>
        <li class="breadcrumb-item active" aria-current="page">Check Data</li>
      </ol>
    </nav>

    <div class="container-fluid">

      <div class="row">
        <div class="col-3">
          <div class="float-right">
            <form method="post">
              {% csrf_token%}
              {% for field in form %}
                <div class="submit-link-row">
                  <h6><b>{{ field.label_tag }}</b></h6>
                  {{ field }}
                  <br><br>
                </div>
                {% if form.errors %}
                  {% for error in field.errors %}
                    <p class="error-message" style="color:red">
                      <strong>{{ error|escape }}</strong>
                    </p>
                  {% endfor %}
                {% endif %}
              {% endfor %}
              
              <input type="submit" class="btn btn-sm btn-primary"  name="check_data" value="Check Data">
            </form>
          </div>
        </div>
        <div class="col-8 col-lg-7">
          <h5 class="text-primary">
            Data report :
          </h5>
          <br>
          <table id='table_id' class="display" style="width:100%">
            <thead>
              <tr>
                <th align="center">ID</th>
                <th align="center">Type</th>
                <th align="center">Message</th>
              </tr>
            </thead>
            <tbody>
              {%for message in data_report %}
                <tr>
                  <td>{{message.id}}</td>
                  <td>{{message.lon}}</td>
                  <td>{{message.file}}</td>
                </tr>
              {% endfor %}
            </tbody>
            <tfoot>
              <tr>
                <th>
                  <button type="button" class="btn btn-sm btn-primary" disabled>
                    Filtering:
                  </button>
                </th>
                <th></th>
                <th></th>
              </tr>
            </tfoot>
          </table>
          <br>
          <b class="text-secondary">Station(s): </b>
          <em class ="text-secondary">
            {% for md in data_report %}
              {% if not forloop.last %}
                {{ md.nslc }},
              {% else %}
                {{ md.nslc }}
              {% endif %}
            {% endfor %}
          </em>
        </div>
      </div>

    </div>
    {% include "home/footer.html" %}
  </body>
  <script>
    $(document).ready( function () {
      $("#qcBtn").addClass("active");
      $("#dataDd").addClass("active");
      $("#logDd").attr("href","/admin/logdb/qclog/")
      var table = $('#table_id').DataTable( {
        initComplete: function () {
          this.api().columns([1,]).every( function () {
              var column = this;
              // var select = $('<select><option value=""></option></select>')
              var select = $('<select><option value="">Show all</option></select>')
                  .appendTo( $(column.footer()).empty() )
                  .on( 'change', function () {
                      var val = $.fn.dataTable.util.escapeRegex(
                          $(this).val()
                      );
                      myMule = val;
                      column
                          .search( val ? '^'+val+'$' : '', true, false )
                          .draw();
                  });
              column.data().unique().sort().each( function ( d, j ) {
                  select.append( '<option value="' + d + '">' + d.substr(0,30) + '</option>' )
              } );
              $( select ).click( function(e) {
                   e.stopPropagation();
             });
          } );
        },
        scrollX: true,
        scrollY: 350,
        scrollCollapse: true,
        paging: false,
        orderCellsTop: true,
        fixedHeader: true,
        "order": [[1,'desc']],
        dom: 'fitp',
        select: {
            style:    'multi',
        },
      });
      table.columns.adjust().draw();
    });
  </script>
</html>

qualitycontrol/templates/qualitycontrol/check_metadata.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Morumotto</title>
    {% include "home/headers/datepicker_datatable.html" %}
  </head>

  <body>

    {% include "home/header.html" %}
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb ">
        <li class="breadcrumb-item"><a href="/qualitycontrol">Quality Control</a></li>
        <li class="breadcrumb-item active" aria-current="page">Check Metadata</li>
      </ol>
    </nav>

    <!-- <div class="container">
      <div class="alert alert-danger" role="alert">
        <i class="fas fa-ghost"></i> Not available yet, currently under development
      </div>
    </div>
    <div class="container-fluid"> -->

      <div class="row">
        <div class="col-3">
          <div class="float-right">
            <form method="post">
              {% csrf_token%}
              {% for field in form %}
                <div class="submit-link-row">
                  <h6><b>{{ field.label_tag }}</b></h6>
                  {{ field }}
                  <br><br>
                </div>
                {% if form.errors %}
                  {% for error in field.errors %}
                    <p class="error-message" style="color:red">
                      <strong>{{ error|escape }}</strong>
                    </p>
                  {% endfor %}
                {% endif %}
              {% endfor %}

              <input type="submit" class="btn btn-sm btn-primary"  name="check_metadata" value="Check Metadata">
            </form>
          </div>
        </div>
        <div class="col-8 col-lg-7">
          <h5 class="text-primary">
            Metadata report :
          </h5>
          <br>
          <table id='table_id' class="display" style="width:100%">
            <thead>
              <tr>
                <th align="center">NSLC</th>
                <th align="center"  style="width: 2px">Type</th>
                <th align="center">Message</th>
                <th align="center">File</th>
              </tr>
            </thead>
            <tbody>
              {% for md in metadata_report %}
                {% for message in md.messages.all %}
                    <tr>
                      <td>{{md.nslc.code}}</td>
                      <td>{{message.type}}</td>
                      <td>{{message.msg}}</td>
                      <td>{{md.file}}</td>
                    </tr>
                {% endfor %}
              {% endfor %}
            </tbody>
            <tfoot>
              <tr>
                <th>
                  <button type="button" class="btn btn-sm btn-primary" disabled>
                    Filtering:
                  </button>
                </th>
                <th></th>
                <th></th>
                <th></th>
              </tr>
            </tfoot>
          </table>
          <br>
          <b class="text-secondary">Station(s): </b>
          <em class ="text-secondary">
            {% for md in metadata_report %}
              {% if not forloop.last %}
                {{ md.nslc }},
              {% else %}
                {{ md.nslc }}
              {% endif %}
            {% endfor %}
          </em>

        </div>
      </div>
    </div>
    {% include "home/footer.html" %}
    <script>
      $(document).ready( function () {
        $("#qcBtn").addClass("active");
        $("#checkMdDd").addClass("active");
        $("#logDd").attr("href","/admin/logdb/qclog/")
        var table = $('#table_id').DataTable( {
          initComplete: function () {
            this.api().columns([1,]).every( function () {
                var column = this;
                // var select = $('<select><option value=""></option></select>')
                var select = $('<select><option value="">Show all</option></select>')
                    .appendTo( $(column.footer()).empty() )
                    .on( 'change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );
                        myMule = val;
                        column
                            .search( val ? '^'+val+'$' : '', true, false )
                            .draw();
                    });
                column.data().unique().sort().each( function ( d, j ) {
                    select.append( '<option value="' + d + '">' + d.substr(0,30) + '</option>' )
                } );
                $( select ).click( function(e) {
                     e.stopPropagation();
               });
            } );
          },
          scrollX: true,
          scrollY: 350,
          scrollCollapse: true,
          paging: false,
          orderCellsTop: true,
          fixedHeader: true,
          "order": [[1,'desc']],
          dom: 'fitp',
          select: {
              style:    'multi',
          },
        });
        table.columns.adjust().draw();
      });
    </script>
  </body>
</html>

qualitycontrol/templates/qualitycontrol/plot_completion.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Morumotto</title>
    {% include "home/headers/datepicker.html" %}
  </head>
  <body>
    {% include "home/header.html" %}
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb ">
        <li class="breadcrumb-item"><a href="/qualitycontrol">Quality Control</a></li>
        <li class="breadcrumb-item active" aria-current="page">Plot data completion</li>
      </ol>
    </nav>

    <div class="container-fluid">

      <div class="row">
        <div class="col-3">
          <div class="float-right">
            <form method="post">
              {% csrf_token%}
              {% for field in form %}
                <div class="submit-link-row">
                  <h6><b>{{ field.label_tag }}</b></h6>
                  {{ field }}
                  <br><br>
                </div>
                {% if form.errors %}
                  {% for error in field.errors %}
                    <p class="error-message" style="color:red">
                      <strong>{{ error|escape }}</strong>
                    </p>
                  {% endfor %}
                {% endif %}
              {% endfor %}
              <br>
              <input type="submit" class="btn btn-sm btn-primary"  name="plot_complt" value="Plot Completion">
            </form>
          </div>
        </div>
        <div class="col-8 col-lg-7">
          {% if figure is True %}
            <h5 class="text-primary">
              Completion :
            </h5>
            <br>

            <img data-enlargable style="cursor: zoom-in" src="{% static plotdir|add:filename_id|add:'.complt.'|add:extension %}" id="plot" />
            <br>
            <em class="text-secondary">
              Start times of traces with available data are marked by crosses, gaps are indicated by vertical red lines.
              Data availability percentage is shown below station N.S.L.C
             </em>
          {% elif figure is not False %}
            <div class="alert alert-danger" role="alert">
              <p><i class="fa fa-exclamation-circle"></i>
                Could not compute plot from data :
                <br>
                ERROR : {{ figure }}
              </p>
            </div>
          {% endif %}
        </div>
      </div>

    </div>
    {% include "home/footer.html" %}
    <script>
      $(document).ready( function () {
        $("#qcBtn").addClass("active");
        $("#completionDd").addClass("active");
        $("#logDd").attr("href","/admin/logdb/qclog/")
        $("#id_year").data("DateTimePicker").defaultDate(new Date());
      });

      $('img[data-enlargable]').addClass('img-enlargable').click(function(){
          var src = $(this).attr('src');
          $('<div>').css({
              background: 'RGBA(0,0,0,.5) url('+src+') no-repeat center',
              backgroundSize: 'contain',
              width:'100%', height:'100%',
              position:'fixed',
              zIndex:'10000',
              top:'0', left:'0',
              cursor: 'zoom-out'
          }).click(function(){
              $(this).remove();
          }).appendTo('body');
      });


    </script>
  </body>

</html>

qualitycontrol/templates/qualitycontrol/plot_response.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Morumotto</title>
    {% include "home/headers/datepicker.html" %}
  </head>

  <body>

    {% include "home/header.html" %}
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb ">
        <li class="breadcrumb-item"><a href="/qualitycontrol">Quality Control</a></li>
        <li class="breadcrumb-item active" aria-current="page">Plot Responses</li>
      </ol>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <div class="col-3">
          <div class="float-right">
            <form method="post">
              {% csrf_token%}
              {% for field in form %}
                <div class="submit-link-row">
                  <h6><b>{{ field.label_tag }}</b></h6>
                  {{ field }}
                  <br><br>
                </div>
                {% if form.errors %}
                  {% for error in field.errors %}
                    <p class="error-message" style="color:red">
                      <strong>{{ error|escape }}</strong>
                    </p>
                  {% endfor %}
                {% endif %}
              {% endfor %}

              <input type="submit" class="btn btn-sm btn-primary"  name="plot_resp" value="Plot Response">
            </form>
          </div>
        </div>
        <div class="col-8 col-lg-7">
          {% if figure is True %}
            <h5 class="text-primary">
              Response :
            </h5>
            <br>
            <img src="{% static plotdir|add:filename_id|add:'.resp.'|add:extension %}" id="plot" />
            <br>
            <b class="text-secondary">Station: </b>
            <em class ="text-secondary">{{ metadata.nslc }}</em>
          {% elif figure is not False %}
            <div class="alert alert-danger" role="alert">
              <p><i class="fa fa-exclamation-circle"></i>
                Could not compute plot from metadata :
                <br>
                ERROR : {{ figure }}
              </p>
            </div>
          {% endif %}
        </div>
      </div>

    </div>

    {% include "home/footer.html" %}
    <script>
      $(document).ready( function () {

        $("#qcBtn").addClass("active");
        $("#responseDd").addClass("active");
        $("#logDd").attr("href","/admin/logdb/qclog/")
      });
    </script>
  </body>
</html>