archive/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views

urlpatterns = [
    path('update', views.update_view, name='index.update'),
    path('stack', views.stack_view, name='index.stack_view'),
    path('newrequest', views.newrequest, name='index.newrequest'),
]

home/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('init_welcome', views.init_welcome, name='init_welcome'),
    # path('init_networks', views.init_networks, name='init_networks'),
    path('init_nslc', views.init_nslc, name='init_nslc'),
    path('init_source', views.init_source, name='init_source'),
    path('init_config', views.init_config, name='init_config'),
    path('init_monitoring', views.init_monitoring, name='init_monitoring'),
    path('init_qcconfig', views.init_qcconfig, name='init_qcconfig'),
    path('init_finish', views.init_finish, name='init_finish'),
    path('import_nslc',views.import_nslc, name='import_nslc'),
    path('about', views.about, name='about'),
    # path('old', views.index_old, name='index.old')
]

morumotto/urls.py
# -*- coding: utf-8 -*-
"""morumotto URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf import settings
from django.conf.urls import url
from home import views as home_views
from . import celery
import object_tools

urlpatterns = [
    path('admin/', admin.site.urls), # URL FOR ADMIN PAGE
    path('home/', include('django.contrib.auth.urls')), #URL FOR AUTHENTICATION PAGE
    # path('accounts/login/', admin.site.urls),
    path('', home_views.go_to_home, name='home'),
    path('home/', include('home.urls')),
    # path('login/', home_views.login, name="login"),
    # path('logout/', home_views.logout, name="logout"),
    path('archive/',include('archive.urls')),
    path('monitoring/',include('monitoring.urls')),
    path('qualitycontrol/',include('qualitycontrol.urls')),
    path('celery_progress/', include('celery_progress.urls')),  # the endpoint is configurable
    # url(r'^celery-progress/', include('celery_progress.urls')),
    path('flower', home_views.flower_redirect, name='flower_redirect'),
    path('rtfm', home_views.documentation_redirect, name='documentation_redirect'),
    path('object-tools/', object_tools.tools.urls),
]

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.index_title = settings.ADMIN_INDEX_TITLE
admin.site.site_title = settings.ADMIN_SITE_TITLE

monitoring/models.py
# -*- coding: utf-8 -*-
from datetime import datetime
from django.db import models
from django.utils.timezone import now
from archive.models import Network, Station, DataFile
from plugins.choices import get_plugin_choices
import importlib
import logging

logger = logging.getLogger('Status')

class Component(models.Model):
    COMP_CHOICES =(
    ('Component', 'Display'),
    ('Other', 'Group as Other'),
    ('Disabled', 'Disable'),
    )
    name = models.CharField(max_length=10)
    view_status = models.CharField(
                max_length=50,
                choices=COMP_CHOICES,
                default='Component')

    def __str__(self):
        return self.name


class ChanPath(models.Model):
    archive = models.CharField(max_length=100)

    net = models.CharField(max_length=50)
    sta = models.CharField(max_length=50)
    loc = models.CharField(max_length=10)
    chan = models.CharField(max_length=50)
    chan_path = models.CharField(max_length=100,default=None)

    def save(self, *args, **kwargs):
        self.chan_path = '{0}.{1}.{2}.{3}'.format(self.net, self.sta, self.loc,
                                             self.chan)
        super(ChanPath, self).save(*args, **kwargs)

    def __str__(self):
        return self.chan_path

    class Meta:
        ordering = ('chan_path',)

class CompPath(models.Model):
    archive = models.CharField(max_length=100)

    net = models.CharField(max_length=50)
    sta = models.CharField(max_length=50)
    loc = models.CharField(max_length=10)
    comp = models.CharField(max_length=10)
    comp_path = models.CharField(max_length=50,default=None)

    def save(self, *args, **kwargs):
        self.comp_path = '{0}.{1}.{2}.{3}'.format(self.net, self.sta, self.loc,
                                             self.comp)
        super(CompPath, self).save(*args, **kwargs)

    def __str__(self):
        return self.comp_path

    class Meta:
        ordering = ('comp_path',)

class ArchiveMonitoring(models.Model):
    DATAFORMAT_CHOICES = get_plugin_choices("format")
    METADATAFORMAT_CHOICES = get_plugin_choices("metadata_format")
    STRUCT_CHOICES = get_plugin_choices("structure")

    archive = models.CharField(max_length=100,
                               help_text='Enter the PATH to the archive '
                                         'you want to monitor',
                               unique=True)
    networks = models.ManyToManyField(Network)
    components = models.ManyToManyField(Component)
    stations = models.ManyToManyField(Station)
    start_year = models.IntegerField(
               default=int(datetime.now().year))
    end_year = models.IntegerField(
             default=int(datetime.now().year))


    data_format = models.CharField(
                max_length=50,
                choices=DATAFORMAT_CHOICES,
                default='miniSEED')
    # metadata_format = models.CharField(
    #                 max_length=50,
    #                 choices=METADATAFORMAT_CHOICES,
    #                 default='DatalessSEED')
    struct_type = models.CharField(
                max_length=50,
                choices=STRUCT_CHOICES,
                default='SDS')

    __original_components = None
    __original_stations = None

    def get_data_structure(self):
        # We will instanciate the correct class according to the structure type.
        # See plugins/structure.py
        try:
            module = importlib.import_module("plugins.structure")
            class_ = getattr(module, self.struct_type)
            return class_()
        except:
            logger.error("ERROR: %s has not yet been implemented."
                  " See plugins/structure.py" % struct_type)
            return 1


    def get_data_format(self):
        # We will instanciate the correct class according to the format type.
        # See plugins/format.py
        try:
            module = importlib.import_module("plugins.format")
            class_ = getattr(module, self.data_format)
            return class_()
        except:
            logger.error("ERROR: %s has not yet been implemented."
                  " See plugins/format.py" % data_format)
            return 1

    # def get_metadata_format(self):
    #     # We will instanciate the correct class according to the metadata format
    #     # See plugins/metadata_format.py
    #     try:
    #         module = importlib.import_module("plugins.metadata_format")
    #         class_ = getattr(module, self.metadata_format)
    #         return class_()
    #     except:
    #         logger.error("ERROR: %s has not yet been implemented."
    #               " See plugins/metadata_format.py" % self.metadata_format)
    #         return 1

    def __str__(self):
        return self.archive

    class Meta:
        verbose_name = 'Monitoring setup'
        verbose_name_plural = 'Monitoring setup'


class Stat(models.Model):

    archive_name = models.CharField(max_length=50)
    net = models.CharField(max_length=50)
    sta = models.CharField(max_length=50)
    loc = models.CharField(max_length=10)
    chan = models.CharField(max_length=50)
    comp = models.CharField(max_length=10)

    day = models.DateField('day')
    year = models.CharField(max_length=4)
    starttime = models.DateTimeField('Stream start time')
    endtime = models.DateTimeField('Stream end time')
    modif_time = models.CharField(max_length=50,default=now)

    datafile = models.ForeignKey(DataFile,on_delete=models.CASCADE)
    timestamp = models.IntegerField(default=0)
    ngaps = models.IntegerField(default=0)
    noverlaps = models.IntegerField(default=0)
    gap_span = models.FloatField(default=0)
    overlap_span = models.FloatField(default=0)
    av_new = models.BooleanField(
           default="True",
           verbose_name='Average New')

    def __str__(self):
        return self.datafile.filename

    class Meta:
        verbose_name = 'Statistics'
        verbose_name_plural = 'Statistics'

class AverageStat(models.Model):
    archive_name = models.CharField(max_length=50)
    net = models.CharField(max_length=50)

    a_timestamp = models.IntegerField(default=0)
    a_gap = models.FloatField(default=0)
    a_overlap = models.FloatField(default=0)

    # def get_net(self):
    #     return self.filter(type="3") # ??

    def __str__(self):
        return self.net

    class Meta:
        verbose_name = 'Statistics by Network (average)'
        verbose_name_plural = 'Statistics by Networks (average)'
        ordering = ('net',)


class AverageCompStat(models.Model):
    archive_name = models.CharField(max_length=50)
    net = models.CharField(max_length=50)
    comp = models.CharField(max_length=10)

    a_comp_timestamp = models.IntegerField(default=0)
    a_comp_gap = models.FloatField(default=0)
    a_comp_overlap = models.FloatField(default=0)

    def __str__(self):
        return self.net + self.comp

    class Meta:
        verbose_name = 'Statistics by Component (average)'
        verbose_name_plural = 'Statistics by Components (average)'
        ordering = ('comp',)


class Metrics(models.Model):
    archive_name = models.CharField(max_length=50)

    mean = models.IntegerField(default=0)
    median = models.IntegerField(default=0)
    min = models.IntegerField(default=0)
    max = models.IntegerField(default=0)
    spikes = models.BooleanField(default=False)
    rms = models.IntegerField(default=0)
    data_avalability = models.IntegerField(default=0)
    ngaps = models.IntegerField(default=0)
    noverlaps = models.IntegerField(default=0)

    def __str__(self):
        return self.objects.id


class UpdateStatStatus(models.Model):
    # file_id = models.IntegerField()
    status = models.CharField(max_length=200, default="None")

archive/forms.py
# -*- coding: utf-8 -*-
from django import forms
from archive.models import GapList, NSLC, Source, Configuration
from bootstrap_datepicker_plus import DateTimePickerInput


class SourceForm(forms.Form):
    source_list = forms.ModelMultipleChoiceField(
                queryset=Source.objects.all(),
                widget=forms.SelectMultiple(
                      attrs={'size': 8, 'style': 'width:100%;'}),
                      label="Select source(s)",
                      help_text="Leave empty if you want the request to ask all"
                      " sources configured for the given NSLC. "
                      "If you select source(s), the request will only ask "
                      "for these sources, ignioring others",
                     required = False,
                     # initial = [s for s in Source.objects.all() if Source.objects.all().count()],
                     )


class WindowForm(forms.ModelForm):
    class Meta:
        model = Configuration
        fields = ['f_analysis', 'l_analysis', 'w_analysis', 'granularity_type']
        widgets = {
            'f_analysis': forms.NumberInput(attrs={'onchange':'update_value()',
                                                   'style': 'width: 100px'}),
            'w_analysis': forms.NumberInput(attrs={'onchange':'update_value()',
                                                   'style': 'width: 100px'}),
            'l_analysis': forms.NumberInput(attrs={'onchange':'update_value()',
                                                   'style': 'width: 100px'}),
            'granularity_type': forms.Select(attrs={'onchange':'update_value()',
                                                    'style': 'width: 100px'}),
            }
    def __init__(self, *args, **kwargs):
        # This is to have a popover help for each fields
        super(WindowForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            help_text = self.fields[field].help_text
            self.fields[field].help_text = None
            if help_text != '':
                self.fields[field].widget.attrs.update({'class':'has-popover',
                                                        'title':help_text,
                                                        'data-placement':'right',
                                                        'data-container':'body'})

    def clean(self):
        f_analysis = self.cleaned_data.get("f_analysis")
        l_analysis = self.cleaned_data.get("l_analysis")
        w_analysis = self.cleaned_data.get("w_analysis")
        if w_analysis < f_analysis :
            raise forms.ValidationError({'f_analysis': ['Frequency of analysis '
                                                'must be <= to '
                                                'the analysis Window'],
                                   'w_analysis':['Analysis window must be >= '
                                                'to the frequency of analysis'],
                                  })
        return self.cleaned_data



class NewRequestForm(forms.ModelForm):
    class Meta:
        model = GapList

        fields = ['nslc_list', 'starttime', 'endtime','force_source']
        widgets = {'starttime': DateTimePickerInput(attrs={'class': 'datetimepicker-input',
                                                            'placeholder':'Select a date',},
                                                    format='YYYY-MM-DD HH:mm:ss'),
                    'endtime': DateTimePickerInput(attrs={'class': 'datetimepicker-input',
                                                          'placeholder':'Select a date'},
                                                  format='YYYY-MM-DD HH:mm:ss'),
                    'nslc_list': forms.SelectMultiple(attrs={'size': 23}),
                    }
        labels = { "nslc_list": "Select NSLC(s)" }
    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("starttime")
        end_date = cleaned_data.get("endtime")

        if end_date and start_date:
            if end_date < start_date:
                msg = "Endtime should be greater than starttime."
                self.add_error("endtime", msg)



# class NSLCForm(forms.Form):
#     nslc_list = forms.ModelMultipleChoiceField(queryset=Metadata.objects.all(),
#                                                widget=forms.SelectMultiple(
#                                                      attrs={'size': 20}),
#                                                label="Select NSLC(s)",
#                                                )

archive/templates/archive/index.newrequest.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <title>Morumotto</title>
  {% include "home/headers/datepicker.html" %}
</head>
<body>
  {% include "home/header.html" %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb ">
      <li class="breadcrumb-item"><a href="/archive/stack">Stack</a></li>
      <li class="breadcrumb-item active" aria-current="page">New Request</li>
    </ol>
  </nav>
  <div class="container">
    <form method="post">
      {% csrf_token %}

      <br>
      <div class="row">
        {% for field in request_form %}
          {% if forloop.first %}
            <div class="col-3">
              <h6><b>{{ field.label_tag }}</h6></b> <br> {{ field }}
            </div>
          {% endif %}
          {% if request_form.errors %}
            {% for error in field.errors %}
              <p class="error-message" style="color:red">
                <strong><i class="fas fa-exclamation-circle"></i>  {{ error|escape }}</strong>
              </p>
            {% endfor %}
          {% endif %}
        {% endfor %}

        <div class="col-5">
          {% for field in request_form %}
            {% if not forloop.first and not forloop.last %}
              <h6><b>{{ field.label_tag }}</h6></b> <br> {{ field }}<br>
            {% endif %}
            {% if request_form.errors %}
              {% for error in field.errors %}
                <p class="error-message" style="color:red">
                  <strong><i class="fas fa-exclamation-circle"></i>  {{ error|escape }}</strong>
                </p>
              {% endfor %}
            {% endif %}
          {% endfor %}

          <br>
          <button type="button" class="btn btn-sm btn-light" data-toggle="modal" data-target="#jdayCal">
            Display Julian Day Calendar
          </button>





        </div>

        <div class="col-3">

          {% for field in source_form %}
            <h6 style="color : #adb5bd"><b>
              {{ field.label_tag }}
            </h6></b>

            <br>
              {{ field }}
              <br><br>
              <input type="button" class="btn btn-sm btn-secondary" value="Clear selection" id="clearSelection">
              &nbsp;
              <i class="text-secondary fas fa-info-circle"
              title="If no source is selected (using the 'Clear selection' button), requests will ask all sources configured for the given NSLC.
If you select source(s), the request will only ask for these sources, ignoring others.">
              </i>
              <!-- {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
              {% endif %} -->
            <br>

            {% if source_form.errors %}
              {% for error in field.errors %}
                <p class="error-message" style="color:red">
                  <strong><i class="fas fa-exclamation-circle"></i>  {{ error|escape }}</strong>
                </p>
              {% endfor %}
            {% endif %}
          {% endfor %}
          <hr>
          {% for field in request_form %}
            {% if forloop.last %}
                <h6><b>{{ field.label_tag }}</h6></b>{{ field }}
                <em class="text-secondary small">{{ field.help_text }}</em><br><br>
            {% endif %}
            {% if request_form.errors %}
              {% for error in field.errors %}
                <p class="error-message" style="color:red">
                  <strong><i class="fas fa-exclamation-circle"></i>  {{ error|escape }}</strong>
                </p>
              {% endfor %}
            {% endif %}
          {% endfor %}
        </div>

      </div>
      <br><br>
      <input type="submit" value="Create Request" name="addRequest" class="btn btn-success" >
    </form>
  </div>

  <!-- Calendar modal -->

  <div class="modal fade" id="jdayCal" tabindex="-1" role="dialog" aria-labelledby="jdayCal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modalTitle">Julian Day Calendar (Non Leap Years)</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <center>
            <img class="img-fluid" src="{% static 'home/images/julian_perpetual.png' %}" id="julianLeap" >
            <br><br>
            <button class="btn btn-sm btn-light active" id="showPerpetual">Non-Leap Year</button>
            <button class="btn btn-sm btn-light" id="showLeap">Leap Year</button>
          </center>
        </div>
      </div>
    </div>
  </div>


  {% include "home/footer.html" %}
</body>
<script>
  $(document).ready( function () {


    $('#showLeap').click( function () {
      $('#modalTitle').text('Julian Day Calendar (Leap Years)');
      $('#showLeap').addClass("active");
      $('#showPerpetual').removeClass("active");
      $('#julianLeap').attr("src","{% static 'home/images/julian_leap.png' %}")
    })

    $('#showPerpetual').click( function () {
      $('#modalTitle').text('Julian Day Calendar (Non Leap Years)');
      $('#showPerpetual').addClass("active");
      $('#showLeap').removeClass("active");
      $('#julianLeap').attr("src","{% static 'home/images/julian_perpetual.png' %}")
    })



    $("#stackBtn").addClass("active");
    $("#requestDd").addClass("active");
    $("#logDd").attr("href","/admin/logdb/updatelog/")

    // Use the day to get dates at midnight by default
    $('#id_starttime').data("DateTimePicker").useCurrent('day');
    $('#id_endtime').data("DateTimePicker").useCurrent('day');
    $('#id_endtime').datetimepicker({
            useCurrent: false
        });
    $("#id_starttime").on("dp.change", function (e) {
        $('#id_endtime').data("DateTimePicker").minDate(e.date);

    });
    $("#id_endtime").on("dp.change", function (e) {
        $('#id_starttime').data("DateTimePicker").maxDate(e.date);

    });


    $('#id_source_list option').prop('title', function(){
      return this.text;
    });


    $("#clearSelection").click(function () {
        $("#id_source_list option:selected").prop("selected", false);;
    });
  });
</script>
</html>

archive/templates/archive/index.stack_view.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <title>Morumotto</title>
  {% include "home/headers/datatable.html" %}
</head>
<body>
  {% include "home/header.html" %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb ">
      <li class="breadcrumb-item active" aria-current="page">Stack</li>
    </ol>
  </nav>
  <div class="container-fluid">
    <p align="center">
      {% if user.is_authenticated %}
        <a id="addRequest" href="/archive/newrequest" class="btn btn-success" role="button"><i class="fas fa-plus"></i> Add Request(s)</a>
        <a id="executeStack" href="/archive/update" class="btn btn-success" role="button"><i class="fas fa-play"></i> Update Archive</a>
      {% else %}
        <button class="btn btn-success" title="Sign in to use" disabled><i class="fas fa-plus"></i> Add Request(s)</button>
        <button class="btn btn-success" title="Sign in to use" disabled><i class="fas fa-play"></i> Update Archive</button>

      {% endif %}
    </p><br>
    <table id='table_id' class="display" style="width:100%">
      <thead>
        <tr>
          <th align="center" style="width: 90px">request id</th>
          <th align="center">NSLC</th>
          <th align="center">Gap id</th>
          <th align="center">Gap starttime</th>
          <th align="center">Gap endtime</th>
          <th align="center">status</th>
          <th align="center" style="width: 5px">timeout</th>
          <th align="center">Postfiles</th>
          <th align="center">Patch</th>
          <th align="center" style="width: 5px">
            <button type="button" id="delete" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">
              Delete
            </button>
          </th>
        </tr>
      </thead>
      <tbody>
        {%for request in request_stack %}
          <tr>
            <td>{{request.pk}}</td>
            <td>
            {% if request.gap.nslc.sta.multiplexing %}
              {{ request.gap.nslc.net.name|add:"."|add:request.gap.nslc.sta.name|add:".*.*"}}
            {% else %}
              {{ request.gap.nslc }}
            {% endif %}
            </td>
            <td>{{request.gap.pk}}</td>
            <td>{{request.gap.starttime|date:"Y-m-d H:i:s"}}</td>
            <td>{{request.gap.endtime|date:"Y-m-d H:i:s"}}</td>
            <td>
              {% if request.status == "succeeded" %}
              <span style="font-size: 1em" class="text-success">
              {% elif request.status == "on_hold" or request.status == "failed" %}
              <span style="font-size: 1em" class="text-danger">
              {% else %}
              <span style="font-size: 1em" class="text-warning">
              {% endif %}
              <b>
                {{request.status}}
              </b>
              </span>
            </td>
            <td>{{request.timeout}}</td>
            <!-- {% with request.postfile.all|first as first_postfile %}
              <td>{{first_postfile.filename}}</td>
            {% endwith %} -->
            <td>
              {% for postfile in request.postfile.iterator %}
                Source: {{postfile.source}} -- File : {{ postfile.filename }}<br>
              {% endfor %}
            <td>{{request.tempdir}}</td>
            <td></td>
          </tr>
        {% endfor %}
      </tbody>
      <tfoot>
        <tr>
          <th>
            <button type="button" class="btn btn-sm btn-primary" disabled>
              Filtering:
            </button>
          </th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </tfoot>
    </table>
  </div>

  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Warning</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete <i type="text" id="checkedboxes" value=""></i> requests from your database?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <form method="post" name="delete request"  id="delete1" >
            {% csrf_token %}
            <!-- <span class="icon-input-btn"><span class="fas fa-minus"></span> -->
            <input id="deleteRequest" type="submit" class="btn btn-danger" value="Delete Requests">
            <!-- </span> -->
          </form>
        </div>
      </div>
    </div>
  </div>

  {% include "home/footer.html" %}
  <script>
    $(document).ready( function () {

      $("#stackBtn").addClass("active");
      $("#stackDd").addClass("active");
      $("#logDd").attr("href","/admin/logdb/updatelog/")
      var table = $('#table_id').DataTable( {
        initComplete: function () {
          this.api().columns([1]).every( function () {
              var column = this;
              // var select = $('<select><option value=""></option></select>')
              var select = $('<select><option value="">Show all</option></select>')
                  .appendTo( $(column.footer()).empty() )
                  .on( 'change', function () {
                      var val = $.fn.dataTable.util.escapeRegex(
                          $(this).val()
                      );
                      myMule = val;
                      column
                          .search( val ? '^'+val+'$' : '', true, false )
                          .draw();
                  });
              column.data().unique().sort().each( function ( d, j ) {
                  select.append( '<option value="' + d + '">' + d.substr(0,30) + '</option>' )
              } );
              $( select ).click( function(e) {
                   e.stopPropagation();
             });
          } );
        },
        scrollX: true,
        scrollY: 450,
        scrollCollapse: true,
        paging: true,
        orderCellsTop: true,
        fixedHeader: true,
        "order": [[5,'asc'],[4,'desc']],
        "deferRender": true,
        "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
        columnDefs: [ {
            orderable: false,
            className: 'select-checkbox',
            targets:   -1
        } ],
        dom: 'fiBtlp',
              buttons: [
                  'selectAll',
                  'selectNone',
              ],
        select: {
            style:    'multi',
            selector: 'td:last-child'
        },
      });

      // Number of selected rows
      $("#delete").click(function(){
        var count = table.rows( { selected: true } ).count();
         $("#checkedboxes").text(" "+count+" ");
      });

      // Send the list of deleted request to the backend
      // Récupérer le form html
      var $deleteForm = $('#delete1');

      $deleteForm.one('submit', function (event) {
        event.preventDefault();
        var selected_data = table.rows( { selected: true } ).data();

        for (var i=0; i < selected_data.length ; i++) {
          var $inputHidden = $('<input name="request_to_delete" type="hidden">');
          $inputHidden.val(selected_data[i][0]);
          $(this).append($inputHidden);
        }

        $(this).submit();
      });






      $('#container').css( 'display', 'block' );
      table.columns.adjust().draw();

      {% if user.is_authenticated %}
        $('#deleteRequest').tooltip({'trigger':'hover', 'title': 'Delete all selected requests'});
        $('#addRequest').tooltip({'trigger':'hover', 'title': 'Create a new request'});
      {% else %}
        $('#delete').attr({"disabled":"true","title":"Sign in to use"});
      {% endif %}


      // setTimeout(function () { location.reload(1); }, 60000); // Reloads page every minutes
    });

  </script>

</body>
</html>

archive/templates/archive/progress_stack.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <script src="{% static 'celery_progress/celery_progress.js' %}"></script>
</head>
<body>

  <div class='progress'>
    <div id='progress-bar' role='progressbar'>&nbsp;</div>
  </div>
  <div id="progress-bar-message">Executing Stack...</div>

<script>

  function customProgress(progressBarElement, progressBarMessageElement, progress) {
    progressBarElement.style.backgroundColor = '#68a9ef';
    progressBarElement.style.width = progress.percent + "%";
    progressBarMessageElement.innerHTML = 'Executing stack : (' + progress.current + '/' + progress.total +' requests proceeded)';
  }

  function customSuccess(progressBarElement, progressBarMessageElement) {
      progressBarElement.style.backgroundColor = '#76ce60';
      progressBarMessageElement.innerHTML = "All request processed ! <a href='/monitoring/update_stats'>You may now update statistics</a>";
  }

  function customError(progressBarElement, progressBarMessageElement) {
    progressBarElement.style.backgroundColor = '#e05260';
      progressBarMessageElement.innerHTML = "An error has occured, see log : <a href='/admin/logdb/statuslog/'>Software Log</a>";
  }

  var progressUrl = "{% url 'celery_progress:task_status' task_id_stack %}";
  $(function () {
    CeleryProgressBar.initProgressBar(progressUrl, {
        onProgress: customProgress,
        onSuccess: customSuccess,
        onError: customError,
    });
  });
</script>

</body>
</html>